ps_app_bundle:
    resource: "@PsAppBundle/Controller/"
    type:     annotation
    prefix:   /

ps_front:
    resource: "@PsFrontBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:  { _locale: en }
    requirements:
        _locale: en|ru

ps_football:
    resource: "@PsFootballBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/football/
    requirements:
        _locale: en|ru

ps_user:
    resource: "@PsUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    defaults:  { _locale: en }
    requirements:
        _locale: en|ru

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/admin
    defaults:  { _locale: en }
    requirements:
        _locale: en|ru

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin
    defaults:  { _locale: en }
    requirements:
        _locale: en|ru

BCCCronManagerBundle:
    resource: "@BCCCronManagerBundle/Resources/config/routing.xml"
    prefix:   /{_locale}/admin/cron-manager