ps_football:
    resource: "@PsFootballBundle/Controller/"
    type:     annotation
    prefix:   /football/

ps_front:
    resource: "@PsFrontBundle/Controller/"
    type:     annotation
    prefix:   /

