security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SLAVS:       ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_SLAVS]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_SLAVS]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: index
            anonymous:    true

    access_control:
        - { path: "^/[a-z]{2}/login$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/[a-z]{2}/register", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/[a-z]{2}/resetting", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/[a-z]{2}/admin/", role: ROLE_ADMIN }
        - { path: "^/[a-z]{2}/service/", role: ROLE_SUPER_ADMIN }